name: DeepISP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.25.0
  - pandas=1.4.4
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - pyyaml
  - jupyter
  - notebook=6.5.2
  - ipython=8.7.0
  - tqdm=4.64.1
  - pip
  - pip:
    - torch>=2.0.0
    - torchvision
    - torchaudio
    - umap-learn