name: imo
channels:
- anaconda
- conda-forge
- pkgs/main
- pytorch
dependencies:
- anyio=3.5.0
- appdirs=1.4.4
- appnope=0.1.2
- argon2-cffi=21.3.0
- argon2-cffi-bindings=21.2.0
- asttokens=2.0.5
- attrs=22.1.0
- backcall=0.2.0
- beautifulsoup4=4.12.2
- blas=1.0
- bleach=4.1.0
- bottleneck=1.3.5
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- ca-certificates=2023.05.30
- certifi=2020.6.20
- cffi=1.15.1
- charset-normalizer=2.0.4
- colorama=0.4.6
- comm=0.1.2
- contourpy=1.0.5
- cryptography=41.0.2
- cycler=0.11.0
- debugpy=1.5.1
- decorator=5.1.1
- defusedxml=0.7.1
- entrypoints=0.4
- executing=0.8.3
- ffmpeg=4.3
- filelock=3.9.0
- fonttools=4.25.0
- freetype=2.12.1
- gettext=0.21.0
- giflib=5.2.1
- gmp=6.2.1
- gmpy2=2.1.2
- gnutls=3.6.15
- icu=58.2
- idna=3.4
- ipykernel=6.19.2
- ipython=8.12.0
- ipython_genutils=0.2.0
- jedi=0.18.1
- jinja2=3.1.2
- joblib=1.2.0
- jpeg=9e
- jsonschema=4.17.3
- jupyter_client=7.4.9
- jupyter_core=5.3.0
- jupyter_server=1.23.4
- jupyterlab_pygments=0.1.2
- kiwisolver=1.4.4
- lame=3.100
- lcms2=2.12
- lerc=3.0
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcxx=16.0.6
- libdeflate=1.17
- libffi=3.4.4
- libgfortran=5.0.0
- libgfortran5=11.3.0
- libiconv=1.16
- libidn2=2.3.4
- liblapack=3.9.0
- libllvm14=14.0.6
- libopenblas=0.3.21
- libpng=1.6.39
- libsodium=1.0.18
- libtasn1=4.19.0
- libtiff=4.5.0
- libunistring=0.9.10
- libwebp=1.2.4
- libwebp-base=1.2.4
- libxml2=2.10.3
- libxslt=1.1.37
- lightgbm=4.0.0
- llvm-openmp=16.0.6
- llvmlite=0.40.0
- lxml=4.9.2
- lz4-c=1.9.4
- markupsafe=2.1.1
- matplotlib=3.7.1
- matplotlib-base=3.7.1
- matplotlib-inline=0.1.6
- mistune=0.8.4
- mkl=2023.2.0
- mkl-service=2.4.0
- mkl_fft=1.3.6
- mkl_random=1.2.2
- mpc=1.1.0
- mpfr=4.0.2
- mpmath=1.3.0
- munkres=1.1.4
- nbclassic=0.5.5
- nbclient=0.5.13
- nbconvert=6.5.4
- nbformat=5.7.0
- ncurses=6.4
- nest-asyncio=1.5.6
- nettle=3.7.3
- networkx=3.1
- notebook=6.5.4
- notebook-shim=0.2.2
- numba=0.57.1
- numexpr=2.8.4
- numpy=1.24.4
- openh264=2.1.1
- openssl=3.0.9
- packaging=23.0
- pandas=1.5.3
- pandocfilters=1.5.0
- parso=0.8.3
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=9.4.0
- pip=23.2.1
- platformdirs=2.5.2
- pooch=1.4.0
- prometheus_client=0.14.1
- prompt-toolkit=3.0.36
- psutil=5.9.0
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pycparser=2.21
- pydicom=2.4.3
- pygments=2.15.1
- pynndescent=0.5.10
- pyopenssl=23.2.0
- pyparsing=3.0.9
- pyrsistent=0.18.0
- pysocks=1.7.1
- python=3.11.4
- python-dateutil=2.8.2
- python-fastjsonschema=2.16.2
- python_abi=3.11
- pytorch=2.0.1
- pytz=2022.7
- pyzmq=23.2.0
- readline=8.2
- requests=2.27.1
- scikit-learn=1.2.2
- scipy=1.10.1
- seaborn=0.12.2
- send2trash=1.8.0
- setuptools=68.0.0
- six=1.16.0
- sniffio=1.2.0
- soupsieve=2.4
- sqlite=3.41.2
- stack_data=0.2.0
- sympy=1.11.1
- tbb=2021.8.0
- terminado=0.17.1
- threadpoolctl=2.2.0
- tinycss2=1.2.1
- tk=8.6.12
- torchaudio=2.0.2
- torchvision=0.15.2
- tornado=6.2
- tqdm=4.66.1
- traitlets=5.7.1
- typing-extensions=4.7.1
- typing_extensions=4.7.1
- tzdata=2023c
- umap-learn=0.5.3
- urllib3=1.26.8
- wcwidth=0.2.5
- webencodings=0.5.1
- websocket-client=0.58.0
- wheel=0.38.4
- xmltodict=0.13.0
- xz=5.4.2
- zeromq=4.3.4
- zlib=1.2.13
- zstd=1.5.5

